# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobSearchResponseFacettenInnerBefristung")

model_instance <- JobSearchResponseFacettenInnerBefristung$new()

test_that("counts", {
  # tests for the property `counts` (object)

  # uncomment below to test the property
  #expect_equal(model.instance$`counts`, "EXPECTED_RESULT")
})

test_that("maxCount", {
  # tests for the property `maxCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`maxCount`, "EXPECTED_RESULT")
})
