# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobDetailsMobilitaet")

model_instance <- JobDetailsMobilitaet$new()

test_that("reisebereitschaft", {
  # tests for the property `reisebereitschaft` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`reisebereitschaft`, "EXPECTED_RESULT")
})
