# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api_instance <- DefaultApi$new()

test_that("EdV1ArbeitgeberlogoHashIDGet", {
  # tests for EdV1ArbeitgeberlogoHashIDGet
  # base path: https://rest.arbeitsagentur.de/jobboerse/jobsuche-service
  # Unternehmen Logo
  # Abrufen des Logos eines Unternehmens
  # @param hash_id character 
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PcV4AppJobsGet", {
  # tests for PcV4AppJobsGet
  # base path: https://rest.arbeitsagentur.de/jobboerse/jobsuche-service
  # Jobsuche via App
  # Die Jobsuche via App ermöglicht verfügbare Jobangebote mit verschiedenen get Parametern zu filtern.
  # @param was character Freitext suche Jobtitel (optional)
  # @param wo character Freitext suche Beschäftigungsort (optional)
  # @param berufsfeld character Freitext suche Berufsfeld (optional)
  # @param page integer Ergebnissseite (optional)
  # @param size integer Anzahl von Ergebnissen (optional)
  # @param arbeitgeber character Arbeitgeber der Stelle (optional)
  # @param veroeffentlichtseit integer Anzahl der Tage, seit der Job veröffentlicht wurde. Kann zwischen 0 und 100 Tagen liegen. (optional)
  # @param zeitarbeit character Gibt an, ob Jobs von Zeitarbeitsfirmen in die Suchergebnisse einbezogen werden sollen (default true). (optional)
  # @param angebotsart integer 1=ARBEIT; 2=SELBSTAENDIGKEIT, 4=AUSBILDUNG/Duales Studium, 34=Praktikum/Trainee (optional)
  # @param befristung integer Semikolon-separierte mehrere Werte möglich (z.B. befristung=1;2) 1 = befristet; 2 = unbefristet (optional)
  # @param arbeitszeit character Semikolon-separierte mehrere Werte möglich (z.B. arbeitszeit=vz;tz) vz=VOLLZEIT, tz=TEILZEIT, snw=SCHICHT_NACHTARBEIT_WOCHENENDE, ho=HEIM_TELEARBEIT, mj=MINIJOB (optional)
  # @param behinderung character  (optional)
  # @param corona character Wenn true, werden nur Jobs die im Kontext von Corona angeboten werden angezeigt. (optional)
  # @param umkreis integer Umkreis in Kilometern von Wo-Parameter. (z.B. 25 oder 200) (optional)
  # @return [JobSearchResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PcV4JobsGet", {
  # tests for PcV4JobsGet
  # base path: https://rest.arbeitsagentur.de/jobboerse/jobsuche-service
  # Jobsuche
  # Die Jobsuche ermöglicht verfügbare Jobangebote mit verschiedenen get Parametern zu filtern.
  # @param was character Freitext suche Jobtitel (optional)
  # @param wo character Freitext suche Beschäftigungsort (optional)
  # @param berufsfeld character Freitext suche Berufsfeld (optional)
  # @param page integer Ergebnissseite (optional)
  # @param size integer Anzahl von Ergebnissen (optional)
  # @param arbeitgeber character Arbeitgeber der Stelle (optional)
  # @param veroeffentlichtseit integer Anzahl der Tage, seit der Job veröffentlicht wurde. Kann zwischen 0 und 100 Tagen liegen. (optional)
  # @param zeitarbeit character Gibt an, ob Jobs von Zeitarbeitsfirmen in die Suchergebnisse einbezogen werden sollen (default true). (optional)
  # @param angebotsart integer 1=ARBEIT; 2=SELBSTAENDIGKEIT, 4=AUSBILDUNG/Duales Studium, 34=Praktikum/Trainee (optional)
  # @param befristung integer Semikolon-separierte mehrere Werte möglich (z.B. befristung=1;2) 1 = befristet; 2 = unbefristet (optional)
  # @param arbeitszeit character Semikolon-separierte mehrere Werte möglich (z.B. arbeitszeit=vz;tz) vz=VOLLZEIT, tz=TEILZEIT, snw=SCHICHT_NACHTARBEIT_WOCHENENDE, ho=HEIM_TELEARBEIT, mj=MINIJOB (optional)
  # @param behinderung character  (optional)
  # @param corona character Wenn true, werden nur Jobs die im Kontext von Corona angeboten werden angezeigt. (optional)
  # @param umkreis integer Umkreis in Kilometern von Wo-Parameter. (z.B. 25 oder 200) (optional)
  # @return [JobSearchResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
