# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobSearchResponseStellenangeboteInner")

model_instance <- JobSearchResponseStellenangeboteInner$new()

test_that("hashId", {
  # tests for the property `hashId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hashId`, "EXPECTED_RESULT")
})

test_that("beruf", {
  # tests for the property `beruf` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`beruf`, "EXPECTED_RESULT")
})

test_that("refnr", {
  # tests for the property `refnr` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`refnr`, "EXPECTED_RESULT")
})

test_that("arbeitgeber", {
  # tests for the property `arbeitgeber` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`arbeitgeber`, "EXPECTED_RESULT")
})

test_that("aktuelleVeroeffentlichungsdatum", {
  # tests for the property `aktuelleVeroeffentlichungsdatum` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`aktuelleVeroeffentlichungsdatum`, "EXPECTED_RESULT")
})

test_that("eintrittsdatum", {
  # tests for the property `eintrittsdatum` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eintrittsdatum`, "EXPECTED_RESULT")
})

test_that("arbeitsort", {
  # tests for the property `arbeitsort` (JobSearchResponseStellenangeboteInnerArbeitsort)

  # uncomment below to test the property
  #expect_equal(model.instance$`arbeitsort`, "EXPECTED_RESULT")
})

test_that("modifikationsTimestamp", {
  # tests for the property `modifikationsTimestamp` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`modifikationsTimestamp`, "EXPECTED_RESULT")
})
