# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobSearchResponseFacettenInner")

model_instance <- JobSearchResponseFacettenInner$new()

test_that("befristung", {
  # tests for the property `befristung` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`befristung`, "EXPECTED_RESULT")
})

test_that("behinderung", {
  # tests for the property `behinderung` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`behinderung`, "EXPECTED_RESULT")
})

test_that("pav", {
  # tests for the property `pav` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`pav`, "EXPECTED_RESULT")
})

test_that("berufsfeld", {
  # tests for the property `berufsfeld` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`berufsfeld`, "EXPECTED_RESULT")
})

test_that("arbeitsort", {
  # tests for the property `arbeitsort` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`arbeitsort`, "EXPECTED_RESULT")
})

test_that("ausbildungsart", {
  # tests for the property `ausbildungsart` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`ausbildungsart`, "EXPECTED_RESULT")
})

test_that("veroeffentlichtseit", {
  # tests for the property `veroeffentlichtseit` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`veroeffentlichtseit`, "EXPECTED_RESULT")
})

test_that("schulbildung", {
  # tests for the property `schulbildung` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`schulbildung`, "EXPECTED_RESULT")
})

test_that("arbeitsort_plz", {
  # tests for the property `arbeitsort_plz` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`arbeitsort_plz`, "EXPECTED_RESULT")
})

test_that("arbeitgeber", {
  # tests for the property `arbeitgeber` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`arbeitgeber`, "EXPECTED_RESULT")
})

test_that("beruf", {
  # tests for the property `beruf` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`beruf`, "EXPECTED_RESULT")
})

test_that("branche", {
  # tests for the property `branche` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`branche`, "EXPECTED_RESULT")
})

test_that("arbeitszeit", {
  # tests for the property `arbeitszeit` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`arbeitszeit`, "EXPECTED_RESULT")
})

test_that("eintrittsdatum", {
  # tests for the property `eintrittsdatum` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`eintrittsdatum`, "EXPECTED_RESULT")
})

test_that("zeitarbeit", {
  # tests for the property `zeitarbeit` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`zeitarbeit`, "EXPECTED_RESULT")
})

test_that("corona", {
  # tests for the property `corona` (JobSearchResponseFacettenInnerBefristung)

  # uncomment below to test the property
  #expect_equal(model.instance$`corona`, "EXPECTED_RESULT")
})
