# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobDetailsArbeitsorteInnerKoordinaten")

model_instance <- JobDetailsArbeitsorteInnerKoordinaten$new()

test_that("lat", {
  # tests for the property `lat` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`lat`, "EXPECTED_RESULT")
})

test_that("lon", {
  # tests for the property `lon` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`lon`, "EXPECTED_RESULT")
})
