# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobDetails")

model_instance <- JobDetails$new()

test_that("aktuelleVeroeffentlichungsdatum", {
  # tests for the property `aktuelleVeroeffentlichungsdatum` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`aktuelleVeroeffentlichungsdatum`, "EXPECTED_RESULT")
})

test_that("angebotsart", {
  # tests for the property `angebotsart` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`angebotsart`, "EXPECTED_RESULT")
})

test_that("arbeitgeber", {
  # tests for the property `arbeitgeber` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`arbeitgeber`, "EXPECTED_RESULT")
})

test_that("branchengruppe", {
  # tests for the property `branchengruppe` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`branchengruppe`, "EXPECTED_RESULT")
})

test_that("branche", {
  # tests for the property `branche` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`branche`, "EXPECTED_RESULT")
})

test_that("arbeitgeberHashId", {
  # tests for the property `arbeitgeberHashId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`arbeitgeberHashId`, "EXPECTED_RESULT")
})

test_that("arbeitsorte", {
  # tests for the property `arbeitsorte` (array[JobDetailsArbeitsorteInner])

  # uncomment below to test the property
  #expect_equal(model.instance$`arbeitsorte`, "EXPECTED_RESULT")
})

test_that("arbeitszeitmodelle", {
  # tests for the property `arbeitszeitmodelle` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`arbeitszeitmodelle`, "EXPECTED_RESULT")
})

test_that("befristung", {
  # tests for the property `befristung` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`befristung`, "EXPECTED_RESULT")
})

test_that("uebernahme", {
  # tests for the property `uebernahme` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`uebernahme`, "EXPECTED_RESULT")
})

test_that("betriebsgroesse", {
  # tests for the property `betriebsgroesse` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`betriebsgroesse`, "EXPECTED_RESULT")
})

test_that("eintrittsdatum", {
  # tests for the property `eintrittsdatum` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eintrittsdatum`, "EXPECTED_RESULT")
})

test_that("ersteVeroeffentlichungsdatum", {
  # tests for the property `ersteVeroeffentlichungsdatum` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ersteVeroeffentlichungsdatum`, "EXPECTED_RESULT")
})

test_that("allianzpartner", {
  # tests for the property `allianzpartner` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`allianzpartner`, "EXPECTED_RESULT")
})

test_that("allianzpartnerUrl", {
  # tests for the property `allianzpartnerUrl` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`allianzpartnerUrl`, "EXPECTED_RESULT")
})

test_that("titel", {
  # tests for the property `titel` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`titel`, "EXPECTED_RESULT")
})

test_that("hashId", {
  # tests for the property `hashId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hashId`, "EXPECTED_RESULT")
})

test_that("beruf", {
  # tests for the property `beruf` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`beruf`, "EXPECTED_RESULT")
})

test_that("modifikationsTimestamp", {
  # tests for the property `modifikationsTimestamp` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`modifikationsTimestamp`, "EXPECTED_RESULT")
})

test_that("stellenbeschreibung", {
  # tests for the property `stellenbeschreibung` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`stellenbeschreibung`, "EXPECTED_RESULT")
})

test_that("refnr", {
  # tests for the property `refnr` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`refnr`, "EXPECTED_RESULT")
})

test_that("fuerFluechtlingeGeeignet", {
  # tests for the property `fuerFluechtlingeGeeignet` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`fuerFluechtlingeGeeignet`, "EXPECTED_RESULT")
})

test_that("nurFuerSchwerbehinderte", {
  # tests for the property `nurFuerSchwerbehinderte` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nurFuerSchwerbehinderte`, "EXPECTED_RESULT")
})

test_that("anzahlOffeneStellen", {
  # tests for the property `anzahlOffeneStellen` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`anzahlOffeneStellen`, "EXPECTED_RESULT")
})

test_that("arbeitgeberAdresse", {
  # tests for the property `arbeitgeberAdresse` (JobDetailsArbeitgeberAdresse)

  # uncomment below to test the property
  #expect_equal(model.instance$`arbeitgeberAdresse`, "EXPECTED_RESULT")
})

test_that("fertigkeiten", {
  # tests for the property `fertigkeiten` (array[JobDetailsFertigkeitenInner])

  # uncomment below to test the property
  #expect_equal(model.instance$`fertigkeiten`, "EXPECTED_RESULT")
})

test_that("mobilitaet", {
  # tests for the property `mobilitaet` (JobDetailsMobilitaet)

  # uncomment below to test the property
  #expect_equal(model.instance$`mobilitaet`, "EXPECTED_RESULT")
})

test_that("fuehrungskompetenzen", {
  # tests for the property `fuehrungskompetenzen` (JobDetailsFuehrungskompetenzen)

  # uncomment below to test the property
  #expect_equal(model.instance$`fuehrungskompetenzen`, "EXPECTED_RESULT")
})

test_that("verguetung", {
  # tests for the property `verguetung` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`verguetung`, "EXPECTED_RESULT")
})

test_that("arbeitgeberdarstellungUrl", {
  # tests for the property `arbeitgeberdarstellungUrl` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`arbeitgeberdarstellungUrl`, "EXPECTED_RESULT")
})

test_that("arbeitgeberdarstellung", {
  # tests for the property `arbeitgeberdarstellung` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`arbeitgeberdarstellung`, "EXPECTED_RESULT")
})

test_that("hauptDkz", {
  # tests for the property `hauptDkz` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hauptDkz`, "EXPECTED_RESULT")
})

test_that("istBetreut", {
  # tests for the property `istBetreut` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`istBetreut`, "EXPECTED_RESULT")
})

test_that("istGoogleJobsRelevant", {
  # tests for the property `istGoogleJobsRelevant` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`istGoogleJobsRelevant`, "EXPECTED_RESULT")
})

test_that("anzeigeAnonym", {
  # tests for the property `anzeigeAnonym` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`anzeigeAnonym`, "EXPECTED_RESULT")
})
