# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobDetailsFuehrungskompetenzen")

model_instance <- JobDetailsFuehrungskompetenzen$new()

test_that("hatVollmacht", {
  # tests for the property `hatVollmacht` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hatVollmacht`, "EXPECTED_RESULT")
})

test_that("hatBudgetverantwortung", {
  # tests for the property `hatBudgetverantwortung` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hatBudgetverantwortung`, "EXPECTED_RESULT")
})
