# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobDetailsArbeitgeberAdresse")

model_instance <- JobDetailsArbeitgeberAdresse$new()

test_that("land", {
  # tests for the property `land` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`land`, "EXPECTED_RESULT")
})

test_that("region", {
  # tests for the property `region` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`region`, "EXPECTED_RESULT")
})

test_that("plz", {
  # tests for the property `plz` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`plz`, "EXPECTED_RESULT")
})

test_that("ort", {
  # tests for the property `ort` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ort`, "EXPECTED_RESULT")
})

test_that("strasse", {
  # tests for the property `strasse` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`strasse`, "EXPECTED_RESULT")
})

test_that("strasseHausnummer", {
  # tests for the property `strasseHausnummer` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`strasseHausnummer`, "EXPECTED_RESULT")
})
