# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobDetailsFertigkeitenInner")

model_instance <- JobDetailsFertigkeitenInner$new()

test_that("hierarchieName", {
  # tests for the property `hierarchieName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`hierarchieName`, "EXPECTED_RESULT")
})

test_that("auspraegungen", {
  # tests for the property `auspraegungen` (object)

  # uncomment below to test the property
  #expect_equal(model.instance$`auspraegungen`, "EXPECTED_RESULT")
})
