# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test JobSearchResponse")

model_instance <- JobSearchResponse$new()

test_that("stellenangebote", {
  # tests for the property `stellenangebote` (array[JobSearchResponseStellenangeboteInner])

  # uncomment below to test the property
  #expect_equal(model.instance$`stellenangebote`, "EXPECTED_RESULT")
})

test_that("maxErgebnisse", {
  # tests for the property `maxErgebnisse` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`maxErgebnisse`, "EXPECTED_RESULT")
})

test_that("page", {
  # tests for the property `page` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`page`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})

test_that("facetten", {
  # tests for the property `facetten` (array[JobSearchResponseFacettenInner])

  # uncomment below to test the property
  #expect_equal(model.instance$`facetten`, "EXPECTED_RESULT")
})
