#' Arbeitsagentur Jobsuche API
#'
#' Die größte Stellendatenbank Deutschlands durchsuchen, Details zu Stellenanzeigen und Informationen über Arbeitgeber abrufen. <br><br>Die Authentifizierung funktioniert über die clientId:<br><br>clientId: jobboerse-jobsuche<br><br>Bei folgenden GET-requests ist die clientId als Header-Parameter 'X-API-Key' zu übergeben.
#'
#' The version of the OpenAPI document: 2.0.2
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Default operations
#' @description DefaultApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  EdV1ArbeitgeberlogoHashIDGet  ####################
#'
#' library(jobsuche)
#' var_hash_id <- "VK2qoXBe0s-UAdH_qxLDRrZrY5iY8a1PJt3MjJCXsdo=" # character |
#'
#' #Unternehmen Logo
#' api_instance <- jobsuche_api$new()
#'
#' # Configure API key authorization: APIKeyHeaders
#' api_instance$api_client$api_keys["X-API-Key"] <- Sys.getenv("API_KEY")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$EdV1ArbeitgeberlogoHashIDGet(var_hash_iddata_file = "result.txt")
#' result <- api_instance$default_api$EdV1ArbeitgeberlogoHashIDGet(var_hash_id)
#' dput(result)
#'
#'
#' ####################  PcV4AppJobsGet  ####################
#'
#' library(jobsuche)
#' var_was <- "Referatsleiter" # character | Freitext suche Jobtitel (Optional)
#' var_wo <- "Berlin" # character | Freitext suche Beschäftigungsort (Optional)
#' var_berufsfeld <- "Informatik" # character | Freitext suche Berufsfeld (Optional)
#' var_page <- 1 # integer | Ergebnissseite (Optional)
#' var_size <- 50 # integer | Anzahl von Ergebnissen (Optional)
#' var_arbeitgeber <- "Deutsche%20Bahn%20AG" # character | Arbeitgeber der Stelle (Optional)
#' var_veroeffentlichtseit <- 30 # integer | Anzahl der Tage, seit der Job veröffentlicht wurde. Kann zwischen 0 und 100 Tagen liegen. (Optional)
#' var_zeitarbeit <- "true" # character | Gibt an, ob Jobs von Zeitarbeitsfirmen in die Suchergebnisse einbezogen werden sollen (default true). (Optional)
#' var_angebotsart <- 1 # integer | 1=ARBEIT; 2=SELBSTAENDIGKEIT, 4=AUSBILDUNG/Duales Studium, 34=Praktikum/Trainee (Optional)
#' var_befristung <- 1 # integer | Semikolon-separierte mehrere Werte möglich (z.B. befristung=1;2) 1 = befristet; 2 = unbefristet (Optional)
#' var_arbeitszeit <- "vz" # character | Semikolon-separierte mehrere Werte möglich (z.B. arbeitszeit=vz;tz) vz=VOLLZEIT, tz=TEILZEIT, snw=SCHICHT_NACHTARBEIT_WOCHENENDE, ho=HEIM_TELEARBEIT, mj=MINIJOB (Optional)
#' var_behinderung <- "true" # character |  (Optional)
#' var_corona <- "true" # character | Wenn true, werden nur Jobs die im Kontext von Corona angeboten werden angezeigt. (Optional)
#' var_umkreis <- 25 # integer | Umkreis in Kilometern von Wo-Parameter. (z.B. 25 oder 200) (Optional)
#'
#' #Jobsuche via App
#' api_instance <- jobsuche_api$new()
#'
#' # Configure API key authorization: APIKeyHeaders
#' api_instance$api_client$api_keys["X-API-Key"] <- Sys.getenv("API_KEY")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$PcV4AppJobsGet(was = var_was, wo = var_wo, berufsfeld = var_berufsfeld, page = var_page, size = var_size, arbeitgeber = var_arbeitgeber, veroeffentlichtseit = var_veroeffentlichtseit, zeitarbeit = var_zeitarbeit, angebotsart = var_angebotsart, befristung = var_befristung, arbeitszeit = var_arbeitszeit, behinderung = var_behinderung, corona = var_corona, umkreis = var_umkreisdata_file = "result.txt")
#' result <- api_instance$default_api$PcV4AppJobsGet(was = var_was, wo = var_wo, berufsfeld = var_berufsfeld, page = var_page, size = var_size, arbeitgeber = var_arbeitgeber, veroeffentlichtseit = var_veroeffentlichtseit, zeitarbeit = var_zeitarbeit, angebotsart = var_angebotsart, befristung = var_befristung, arbeitszeit = var_arbeitszeit, behinderung = var_behinderung, corona = var_corona, umkreis = var_umkreis)
#' dput(result)
#'
#'
#' ####################  PcV4JobsGet  ####################
#'
#' library(jobsuche)
#' var_was <- "Referatsleiter" # character | Freitext suche Jobtitel (Optional)
#' var_wo <- "Berlin" # character | Freitext suche Beschäftigungsort (Optional)
#' var_berufsfeld <- "Informatik" # character | Freitext suche Berufsfeld (Optional)
#' var_page <- 1 # integer | Ergebnissseite (Optional)
#' var_size <- 50 # integer | Anzahl von Ergebnissen (Optional)
#' var_arbeitgeber <- "Deutsche%20Bahn%20AG" # character | Arbeitgeber der Stelle (Optional)
#' var_veroeffentlichtseit <- 30 # integer | Anzahl der Tage, seit der Job veröffentlicht wurde. Kann zwischen 0 und 100 Tagen liegen. (Optional)
#' var_zeitarbeit <- "true" # character | Gibt an, ob Jobs von Zeitarbeitsfirmen in die Suchergebnisse einbezogen werden sollen (default true). (Optional)
#' var_angebotsart <- 1 # integer | 1=ARBEIT; 2=SELBSTAENDIGKEIT, 4=AUSBILDUNG/Duales Studium, 34=Praktikum/Trainee (Optional)
#' var_befristung <- 1 # integer | Semikolon-separierte mehrere Werte möglich (z.B. befristung=1;2) 1 = befristet; 2 = unbefristet (Optional)
#' var_arbeitszeit <- "vz" # character | Semikolon-separierte mehrere Werte möglich (z.B. arbeitszeit=vz;tz) vz=VOLLZEIT, tz=TEILZEIT, snw=SCHICHT_NACHTARBEIT_WOCHENENDE, ho=HEIM_TELEARBEIT, mj=MINIJOB (Optional)
#' var_behinderung <- "true" # character |  (Optional)
#' var_corona <- "true" # character | Wenn true, werden nur Jobs die im Kontext von Corona angeboten werden angezeigt. (Optional)
#' var_umkreis <- 25 # integer | Umkreis in Kilometern von Wo-Parameter. (z.B. 25 oder 200) (Optional)
#'
#' #Jobsuche
#' api_instance <- jobsuche_api$new()
#'
#' # Configure API key authorization: APIKeyHeaders
#' api_instance$api_client$api_keys["X-API-Key"] <- Sys.getenv("API_KEY")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$PcV4JobsGet(was = var_was, wo = var_wo, berufsfeld = var_berufsfeld, page = var_page, size = var_size, arbeitgeber = var_arbeitgeber, veroeffentlichtseit = var_veroeffentlichtseit, zeitarbeit = var_zeitarbeit, angebotsart = var_angebotsart, befristung = var_befristung, arbeitszeit = var_arbeitszeit, behinderung = var_behinderung, corona = var_corona, umkreis = var_umkreisdata_file = "result.txt")
#' result <- api_instance$default_api$PcV4JobsGet(was = var_was, wo = var_wo, berufsfeld = var_berufsfeld, page = var_page, size = var_size, arbeitgeber = var_arbeitgeber, veroeffentlichtseit = var_veroeffentlichtseit, zeitarbeit = var_zeitarbeit, angebotsart = var_angebotsart, befristung = var_befristung, arbeitszeit = var_arbeitszeit, behinderung = var_behinderung, corona = var_corona, umkreis = var_umkreis)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
DefaultApi <- R6::R6Class(
  "DefaultApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new DefaultApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Unternehmen Logo
    #'
    #' @param hash_id
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return data.frame
    EdV1ArbeitgeberlogoHashIDGet = function(hash_id, data_file = NULL, ...) {
      local_var_response <- self$EdV1ArbeitgeberlogoHashIDGetWithHttpInfo(hash_id, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Unternehmen Logo
    #'
    #' @param hash_id
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (data.frame) with additional information such as HTTP status code, headers
    EdV1ArbeitgeberlogoHashIDGetWithHttpInfo = function(hash_id, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`hash_id`)) {
        stop("Missing required parameter `hash_id`.")
      }


      local_var_url_path <- "/ed/v1/arbeitgeberlogo/{hashID}"
      if (!missing(`hash_id`)) {
        local_var_url_path <- gsub("\\{hashID\\}", URLencode(as.character(`hash_id`), reserved = TRUE), local_var_url_path)
      }

      # API key authentication
      if ("X-API-Key" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["X-API-Key"]) > 0) {
        header_params["X-API-Key"] <- paste(unlist(self$api_client$api_keys["X-API-Key"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("image/png")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "data.frame"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      }

      local_var_error_msg <- local_var_resp$response_as_text()
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Jobsuche via App
    #'
    #' @param was (optional) Freitext suche Jobtitel
    #' @param wo (optional) Freitext suche Beschäftigungsort
    #' @param berufsfeld (optional) Freitext suche Berufsfeld
    #' @param page (optional) Ergebnissseite
    #' @param size (optional) Anzahl von Ergebnissen
    #' @param arbeitgeber (optional) Arbeitgeber der Stelle
    #' @param veroeffentlichtseit (optional) Anzahl der Tage, seit der Job veröffentlicht wurde. Kann zwischen 0 und 100 Tagen liegen.
    #' @param zeitarbeit (optional) Gibt an, ob Jobs von Zeitarbeitsfirmen in die Suchergebnisse einbezogen werden sollen (default true).
    #' @param angebotsart (optional) 1=ARBEIT; 2=SELBSTAENDIGKEIT, 4=AUSBILDUNG/Duales Studium, 34=Praktikum/Trainee
    #' @param befristung (optional) Semikolon-separierte mehrere Werte möglich (z.B. befristung=1;2) 1 = befristet; 2 = unbefristet
    #' @param arbeitszeit (optional) Semikolon-separierte mehrere Werte möglich (z.B. arbeitszeit=vz;tz) vz=VOLLZEIT, tz=TEILZEIT, snw=SCHICHT_NACHTARBEIT_WOCHENENDE, ho=HEIM_TELEARBEIT, mj=MINIJOB
    #' @param behinderung (optional) No description
    #' @param corona (optional) Wenn true, werden nur Jobs die im Kontext von Corona angeboten werden angezeigt.
    #' @param umkreis (optional) Umkreis in Kilometern von Wo-Parameter. (z.B. 25 oder 200)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return JobSearchResponse
    PcV4AppJobsGet = function(was = NULL, wo = NULL, berufsfeld = NULL, page = NULL, size = NULL, arbeitgeber = NULL, veroeffentlichtseit = NULL, zeitarbeit = NULL, angebotsart = NULL, befristung = NULL, arbeitszeit = NULL, behinderung = NULL, corona = NULL, umkreis = NULL, data_file = NULL, ...) {
      local_var_response <- self$PcV4AppJobsGetWithHttpInfo(was, wo, berufsfeld, page, size, arbeitgeber, veroeffentlichtseit, zeitarbeit, angebotsart, befristung, arbeitszeit, behinderung, corona, umkreis, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Jobsuche via App
    #'
    #' @param was (optional) Freitext suche Jobtitel
    #' @param wo (optional) Freitext suche Beschäftigungsort
    #' @param berufsfeld (optional) Freitext suche Berufsfeld
    #' @param page (optional) Ergebnissseite
    #' @param size (optional) Anzahl von Ergebnissen
    #' @param arbeitgeber (optional) Arbeitgeber der Stelle
    #' @param veroeffentlichtseit (optional) Anzahl der Tage, seit der Job veröffentlicht wurde. Kann zwischen 0 und 100 Tagen liegen.
    #' @param zeitarbeit (optional) Gibt an, ob Jobs von Zeitarbeitsfirmen in die Suchergebnisse einbezogen werden sollen (default true).
    #' @param angebotsart (optional) 1=ARBEIT; 2=SELBSTAENDIGKEIT, 4=AUSBILDUNG/Duales Studium, 34=Praktikum/Trainee
    #' @param befristung (optional) Semikolon-separierte mehrere Werte möglich (z.B. befristung=1;2) 1 = befristet; 2 = unbefristet
    #' @param arbeitszeit (optional) Semikolon-separierte mehrere Werte möglich (z.B. arbeitszeit=vz;tz) vz=VOLLZEIT, tz=TEILZEIT, snw=SCHICHT_NACHTARBEIT_WOCHENENDE, ho=HEIM_TELEARBEIT, mj=MINIJOB
    #' @param behinderung (optional) No description
    #' @param corona (optional) Wenn true, werden nur Jobs die im Kontext von Corona angeboten werden angezeigt.
    #' @param umkreis (optional) Umkreis in Kilometern von Wo-Parameter. (z.B. 25 oder 200)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (JobSearchResponse) with additional information such as HTTP status code, headers
    PcV4AppJobsGetWithHttpInfo = function(was = NULL, wo = NULL, berufsfeld = NULL, page = NULL, size = NULL, arbeitgeber = NULL, veroeffentlichtseit = NULL, zeitarbeit = NULL, angebotsart = NULL, befristung = NULL, arbeitszeit = NULL, behinderung = NULL, corona = NULL, umkreis = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE















      query_params[["was"]] <- `was`

      query_params[["wo"]] <- `wo`

      query_params[["berufsfeld"]] <- `berufsfeld`

      query_params[["page"]] <- `page`

      query_params[["size"]] <- `size`

      query_params[["arbeitgeber"]] <- `arbeitgeber`

      query_params[["veroeffentlichtseit"]] <- `veroeffentlichtseit`

      query_params[["zeitarbeit"]] <- `zeitarbeit`

      if (!is.null(`angebotsart`) && !(`angebotsart` %in% c("1", "2", "4", "34"))) {
        stop("Invalid value for angebotsart when calling DefaultApi$PcV4AppJobsGet. Must be [1, 2, 4, 34].")
      }
      query_params[["angebotsart"]] <- `angebotsart`

      if (!is.null(`befristung`) && !(`befristung` %in% c("1", "2"))) {
        stop("Invalid value for befristung when calling DefaultApi$PcV4AppJobsGet. Must be [1, 2].")
      }
      query_params[["befristung"]] <- `befristung`

      if (!is.null(`arbeitszeit`) && !(`arbeitszeit` %in% c("vz", "tz", "snw", "ho", "mj"))) {
        stop("Invalid value for arbeitszeit when calling DefaultApi$PcV4AppJobsGet. Must be [vz, tz, snw, ho, mj].")
      }
      query_params[["arbeitszeit"]] <- `arbeitszeit`

      query_params[["behinderung"]] <- `behinderung`

      query_params[["corona"]] <- `corona`

      query_params[["umkreis"]] <- `umkreis`

      local_var_url_path <- "/pc/v4/app/jobs"
      # API key authentication
      if ("X-API-Key" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["X-API-Key"]) > 0) {
        header_params["X-API-Key"] <- paste(unlist(self$api_client$api_keys["X-API-Key"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "JobSearchResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      }

      local_var_error_msg <- local_var_resp$response_as_text()
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Jobsuche
    #'
    #' @param was (optional) Freitext suche Jobtitel
    #' @param wo (optional) Freitext suche Beschäftigungsort
    #' @param berufsfeld (optional) Freitext suche Berufsfeld
    #' @param page (optional) Ergebnissseite
    #' @param size (optional) Anzahl von Ergebnissen
    #' @param arbeitgeber (optional) Arbeitgeber der Stelle
    #' @param veroeffentlichtseit (optional) Anzahl der Tage, seit der Job veröffentlicht wurde. Kann zwischen 0 und 100 Tagen liegen.
    #' @param zeitarbeit (optional) Gibt an, ob Jobs von Zeitarbeitsfirmen in die Suchergebnisse einbezogen werden sollen (default true).
    #' @param angebotsart (optional) 1=ARBEIT; 2=SELBSTAENDIGKEIT, 4=AUSBILDUNG/Duales Studium, 34=Praktikum/Trainee
    #' @param befristung (optional) Semikolon-separierte mehrere Werte möglich (z.B. befristung=1;2) 1 = befristet; 2 = unbefristet
    #' @param arbeitszeit (optional) Semikolon-separierte mehrere Werte möglich (z.B. arbeitszeit=vz;tz) vz=VOLLZEIT, tz=TEILZEIT, snw=SCHICHT_NACHTARBEIT_WOCHENENDE, ho=HEIM_TELEARBEIT, mj=MINIJOB
    #' @param behinderung (optional) No description
    #' @param corona (optional) Wenn true, werden nur Jobs die im Kontext von Corona angeboten werden angezeigt.
    #' @param umkreis (optional) Umkreis in Kilometern von Wo-Parameter. (z.B. 25 oder 200)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return JobSearchResponse
    PcV4JobsGet = function(was = NULL, wo = NULL, berufsfeld = NULL, page = NULL, size = NULL, arbeitgeber = NULL, veroeffentlichtseit = NULL, zeitarbeit = NULL, angebotsart = NULL, befristung = NULL, arbeitszeit = NULL, behinderung = NULL, corona = NULL, umkreis = NULL, data_file = NULL, ...) {
      local_var_response <- self$PcV4JobsGetWithHttpInfo(was, wo, berufsfeld, page, size, arbeitgeber, veroeffentlichtseit, zeitarbeit, angebotsart, befristung, arbeitszeit, behinderung, corona, umkreis, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Jobsuche
    #'
    #' @param was (optional) Freitext suche Jobtitel
    #' @param wo (optional) Freitext suche Beschäftigungsort
    #' @param berufsfeld (optional) Freitext suche Berufsfeld
    #' @param page (optional) Ergebnissseite
    #' @param size (optional) Anzahl von Ergebnissen
    #' @param arbeitgeber (optional) Arbeitgeber der Stelle
    #' @param veroeffentlichtseit (optional) Anzahl der Tage, seit der Job veröffentlicht wurde. Kann zwischen 0 und 100 Tagen liegen.
    #' @param zeitarbeit (optional) Gibt an, ob Jobs von Zeitarbeitsfirmen in die Suchergebnisse einbezogen werden sollen (default true).
    #' @param angebotsart (optional) 1=ARBEIT; 2=SELBSTAENDIGKEIT, 4=AUSBILDUNG/Duales Studium, 34=Praktikum/Trainee
    #' @param befristung (optional) Semikolon-separierte mehrere Werte möglich (z.B. befristung=1;2) 1 = befristet; 2 = unbefristet
    #' @param arbeitszeit (optional) Semikolon-separierte mehrere Werte möglich (z.B. arbeitszeit=vz;tz) vz=VOLLZEIT, tz=TEILZEIT, snw=SCHICHT_NACHTARBEIT_WOCHENENDE, ho=HEIM_TELEARBEIT, mj=MINIJOB
    #' @param behinderung (optional) No description
    #' @param corona (optional) Wenn true, werden nur Jobs die im Kontext von Corona angeboten werden angezeigt.
    #' @param umkreis (optional) Umkreis in Kilometern von Wo-Parameter. (z.B. 25 oder 200)
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (JobSearchResponse) with additional information such as HTTP status code, headers
    PcV4JobsGetWithHttpInfo = function(was = NULL, wo = NULL, berufsfeld = NULL, page = NULL, size = NULL, arbeitgeber = NULL, veroeffentlichtseit = NULL, zeitarbeit = NULL, angebotsart = NULL, befristung = NULL, arbeitszeit = NULL, behinderung = NULL, corona = NULL, umkreis = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE















      query_params[["was"]] <- `was`

      query_params[["wo"]] <- `wo`

      query_params[["berufsfeld"]] <- `berufsfeld`

      query_params[["page"]] <- `page`

      query_params[["size"]] <- `size`

      query_params[["arbeitgeber"]] <- `arbeitgeber`

      query_params[["veroeffentlichtseit"]] <- `veroeffentlichtseit`

      query_params[["zeitarbeit"]] <- `zeitarbeit`

      if (!is.null(`angebotsart`) && !(`angebotsart` %in% c("1", "2", "4", "34"))) {
        stop("Invalid value for angebotsart when calling DefaultApi$PcV4JobsGet. Must be [1, 2, 4, 34].")
      }
      query_params[["angebotsart"]] <- `angebotsart`

      if (!is.null(`befristung`) && !(`befristung` %in% c("1", "2"))) {
        stop("Invalid value for befristung when calling DefaultApi$PcV4JobsGet. Must be [1, 2].")
      }
      query_params[["befristung"]] <- `befristung`

      if (!is.null(`arbeitszeit`) && !(`arbeitszeit` %in% c("vz", "tz", "snw", "ho", "mj"))) {
        stop("Invalid value for arbeitszeit when calling DefaultApi$PcV4JobsGet. Must be [vz, tz, snw, ho, mj].")
      }
      query_params[["arbeitszeit"]] <- `arbeitszeit`

      query_params[["behinderung"]] <- `behinderung`

      query_params[["corona"]] <- `corona`

      query_params[["umkreis"]] <- `umkreis`

      local_var_url_path <- "/pc/v4/jobs"
      # API key authentication
      if ("X-API-Key" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["X-API-Key"]) > 0) {
        header_params["X-API-Key"] <- paste(unlist(self$api_client$api_keys["X-API-Key"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "JobSearchResponse"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      }

      local_var_error_msg <- local_var_resp$response_as_text()
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
